automation:
  - alias: "Door Locks"
    trigger:
      - platform: mqtt
        topic: "august/+"
    action:
      - service: notify.html5
        data_template:
          message: >
            The {{ trigger.payload_json.lock }} was {{ trigger.payload_json.state }} by {{ trigger.payload_json.user }} at {{ trigger.payload_json.time | timestamp_custom('%I:%M %p', True) }}.
          title: 'Maravilla: {{ trigger.payload_json.lock }}'
          data:
            requireInteraction: True
sensor:
  - platform: mqtt
    state_topic: august/Front-Door
    name: door_lock_front
    value_template: >
      {%- if value_json.state == 'locked' -%}
        on
      {%- else -%}
        off
      {%- endif -%}
  - platform: mqtt
    state_topic: august/Rear-Door
    name: door_lock_rear
    value_template: >
      {%- if value_json.state == 'locked' -%}
        on
      {%- else -%}
        off
      {%- endif -%}
  - platform: mqtt
    state_topic: august/4th-Bedroom
    name: door_lock_4th_bedroom
    value_template: >
      {%- if value_json.state == 'locked' -%}
        on
      {%- else -%}
        off
      {%- endif -%}
group:
  door_locks:
    name: Door Locks
    entities:
      - sensor.door_lock_front
      - sensor.door_lock_rear
      - sensor.door_lock_4th_bedroom