sensor:
  - platform: template
    sensors:
      door_batteries_door_fourth_bedroom:
        value_template: '{{states["zwave"]["door_fourth_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Fourth Bedroom
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["door_fourth_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
      door_batteries_door_front_door:
        value_template: '{{states["zwave"]["door_front_door"]["attributes"]["battery_level"]}}'
        friendly_name: Front Door
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["door_front_door"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
      door_batteries_door_garage_interior:
        value_template: '{{states["zwave"]["door_garage_interior"]["attributes"]["battery_level"]}}'
        friendly_name: Garage (interior)
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["door_garage_interior"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
      door_batteries_door_garage_side:
        value_template: '{{states["zwave"]["door_garage_side"]["attributes"]["battery_level"]}}'
        friendly_name: Garage (side door)
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["door_garage_side"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
      door_batteries_door_rear_door:
        value_template: '{{states["zwave"]["door_rear_door"]["attributes"]["battery_level"]}}'
        friendly_name: Rear Door
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["door_rear_door"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
      slider_batteries_slider_fourth_bedroom:
        value_template: '{{states["zwave"]["slider_fourth_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Fourth Bedroom
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["slider_fourth_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
      slider_batteries_slider_living_room:
        value_template: '{{states["zwave"]["slider_living_room"]["attributes"]["battery_level"]}}'
        friendly_name: Living Room
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["slider_living_room"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
      slider_batteries_slider_master_bedroom:
        value_template: '{{states["zwave"]["slider_master_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Master Bedroom
        unit_of_measurement: '%'
        icon_template: >-
          {% set level = ((states["zwave"]["slider_master_bedroom"]["attributes"]["battery_level"]*0.1)|round)*10|int %}
            mdi:battery
          {%- if level > 90 -%}

          {%- elif level > 70 or ( level < 31 and level > 10 ) -%}
            -{{ level }}
          {%- elif level > 50 -%}
            -60
          {%- elif level > 30 -%}
            -40
          {%- else -%}
            -alert
          {%- endif -%}
group:
  doors:
    name: Doors
    entities:
      - binary_sensor.door_fourth_bedroom_sensor
      - binary_sensor.door_front_door_sensor
      - binary_sensor.door_garage_interior_sensor
      - binary_sensor.door_garage_side_sensor
      - binary_sensor.door_rear_door_sensor
      - binary_sensor.slider_fourth_bedroom_sensor
      - binary_sensor.slider_living_room_sensor
      - binary_sensor.slider_master_bedroom_sensor
  door_batteries:
    name: Doors
    entities:
      - sensor.door_batteries_door_fourth_bedroom
      - sensor.door_batteries_door_front_door
      - sensor.door_batteries_door_garage_interior
      - sensor.door_batteries_door_garage_side
      - sensor.door_batteries_door_rear_door
  slider_batteries:
    name: Sliding Doors
    entities:
      - sensor.slider_batteries_slider_fourth_bedroom
      - sensor.slider_batteries_slider_living_room
      - sensor.slider_batteries_slider_master_bedroom

history_graph:
  doors:
    name: Doors
    hours_to_show: 24
    refresh: 120
    entities:
      - binary_sensor.door_front_door_sensor
      - lock.lock_front_door_locked
      - binary_sensor.door_rear_door_sensor
      - lock.lock_rear_door_locked
      - binary_sensor.door_fourth_bedroom_sensor
      - lock.lock_4thbedroom_door_locked
      - binary_sensor.door_garage_side_sensor
      - lock.lock_garageside_door_locked
