automation:
  - alias: "Front Door Lock"
    trigger:
      - platform: mqtt
        topic: "august/Front-Door"
      - platform: mqtt
        topic: "august/Rear-Door"
      - platform: mqtt
        topic: "august/4th-Bedroom"
    condition:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state != 'None' }}"
    action:
      - service: notify.html5
        data_template:
          message: 'Door state changed'
          title: 'Maravilla: {{ trigger.to_state.name }}'
          data:
            requireInteraction: True
      - service: notify.html5
        data_template:
          message: '{{ trigger.payload_json.time }}: The {{ trigger.payload_json.lock }} has been {{ trigger.payload_json.state }} by {{ trigger.payload.user }}.'
          title: 'Maravilla: {{ trigger.payload_json.lock }}'
          icon: '{{ trigger.payload_json.user-photo }}'
          data:
            requireInteraction: True
sensor:
  - platform: mqtt
    state_topic: august/Front-Door
    name: door_lock_front
  - platform: mqtt
    state_topic: august/Rear-Door
    name: door_lock_rear
  - platform: mqtt
    state_topic: august/4th-Bedroom
    name: door_lock_4th_bedroom
