#automation:
#  - alias: 1BR Check-in
#    trigger:
#      - platform: time
#        at: '14:45:00'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: calendar.airbnb_1br
#          state: 'on'
#        - condition: template
#          value_template: "{% {{ states.calendar.airbnb_1br.attributes.start_time|replace(' 00:00:00','')|replace('-','') }} == {{ now().year }}{{ now().month }}{{ now().day }} %}"
#    action:
#      - service: lock.set_usercode
#        data:
#          node_id: 11
#          code_slot: 3
#          usercode:
#      - service: variable.set_variable
#        data:
#          variable: airbnb_1br_booking
#          value: '{{ calendar.airbnb_1br.attributes.message }}'
#  - alias: 1BR Check-out
#    trigger:
#      - platform: time
#        at: '12:15:00'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: calendar.airbnb_1br
#          state: 'on'
#    action:
#      - service: lock.set_usercode
#        data:
#          node: 11
#          codeslot: 3
#          usercode: !secret 1br_temp_code

group:
  keypad_front:
    name: Front Door Keypad
    view: yes
    icon: mdi:dialpad
    entities:
      - group.door_keypad_front_1
      - group.door_keypad_front_2
      - group.door_keypad_front_3
      - group.door_keypad_front_4
      - group.door_keypad_front_5
      - group.door_keypad_front_6
      - group.door_keypad_front_7
      - group.door_keypad_front_8
      - group.door_keypad_front_9
      - group.door_keypad_front_10

  door_keypad_1:
    name: Pin Code 1
    entities:
      - input_text.door_keypad_1_name
      - input_text.door_keypad_1_code
      - input_select.door_keypad_1_access_schedule
      - input_datetime.door_keypad_1_date_start
      - input_datetime.door_keypad_1_date_end
      - input_boolean.door_keypad_1_front_switch
      - input_boolean.door_keypad_1_rear_switch
      - input_boolean.door_keypad_1_garage_side_switch
      - input_boolean.door_keypad_1_4th_bedroom_switch
  door_keypad_2:
    name: Pin Code 2
    entities:
      - input_text.door_keypad_2_name
      - input_text.door_keypad_2_code
      - input_select.door_keypad_2_access_schedule
      - input_datetime.door_keypad_2_date_start
      - input_datetime.door_keypad_2_date_end
      - input_boolean.door_keypad_2_front_switch
      - input_boolean.door_keypad_2_rear_switch
      - input_boolean.door_keypad_2_garage_side_switch
      - input_boolean.door_keypad_2_4th_bedroom_switch
  door_keypad_3:
    name: Pin Code 3
    entities:
      - input_text.door_keypad_3_name
      - input_text.door_keypad_3_code
      - input_select.door_keypad_3_access_schedule
      - input_datetime.door_keypad_3_date_start
      - input_datetime.door_keypad_3_date_end
      - input_boolean.door_keypad_3_front_switch
      - input_boolean.door_keypad_3_rear_switch
      - input_boolean.door_keypad_3_garage_side_switch
      - input_boolean.door_keypad_3_4th_bedroom_switch
  door_keypad_4:
    name: Pin Code 4
    entities:
      - input_text.door_keypad_4_name
      - input_text.door_keypad_4_code
      - input_select.door_keypad_4_access_schedule
      - input_datetime.door_keypad_4_date_start
      - input_datetime.door_keypad_4_date_end
      - input_boolean.door_keypad_4_front_switch
      - input_boolean.door_keypad_4_rear_switch
      - input_boolean.door_keypad_4_garage_side_switch
      - input_boolean.door_keypad_4_4th_bedroom_switch
  door_keypad_5:
    name: Pin Code 5
    entities:
      - input_text.door_keypad_5_name
      - input_text.door_keypad_5_code
      - input_select.door_keypad_5_access_schedule
      - input_datetime.door_keypad_5_date_start
      - input_datetime.door_keypad_5_date_end
      - input_boolean.door_keypad_5_front_switch
      - input_boolean.door_keypad_5_rear_switch
      - input_boolean.door_keypad_5_garage_side_switch
      - input_boolean.door_keypad_5_4th_bedroom_switch
  door_keypad_6:
    name: Pin Code 6
    entities:
      - input_text.door_keypad_6_name
      - input_text.door_keypad_6_code
      - input_select.door_keypad_6_access_schedule
      - input_datetime.door_keypad_6_date_start
      - input_datetime.door_keypad_6_date_end
      - input_boolean.door_keypad_6_front_switch
      - input_boolean.door_keypad_6_rear_switch
      - input_boolean.door_keypad_6_garage_side_switch
      - input_boolean.door_keypad_6_4th_bedroom_switch
  door_keypad_7:
    name: Pin Code 7
    entities:
      - input_text.door_keypad_7_name
      - input_text.door_keypad_7_code
      - input_select.door_keypad_7_access_schedule
      - input_datetime.door_keypad_7_date_start
      - input_datetime.door_keypad_7_date_end
      - input_boolean.door_keypad_7_front_switch
      - input_boolean.door_keypad_7_rear_switch
      - input_boolean.door_keypad_7_garage_side_switch
      - input_boolean.door_keypad_7_4th_bedroom_switch
  door_keypad_8:
    name: Pin Code 8
    entities:
      - input_text.door_keypad_8_name
      - input_text.door_keypad_8_code
      - input_select.door_keypad_8_access_schedule
      - input_datetime.door_keypad_8_date_start
      - input_datetime.door_keypad_8_date_end
      - input_boolean.door_keypad_8_front_switch
      - input_boolean.door_keypad_8_rear_switch
      - input_boolean.door_keypad_8_garage_side_switch
      - input_boolean.door_keypad_8_4th_bedroom_switch
  door_keypad_9:
    name: Pin Code 9
    entities:
      - input_text.door_keypad_9_name
      - input_text.door_keypad_9_code
      - input_select.door_keypad_9_access_schedule
      - input_datetime.door_keypad_9_date_start
      - input_datetime.door_keypad_9_date_end
      - input_boolean.door_keypad_9_front_switch
      - input_boolean.door_keypad_9_rear_switch
      - input_boolean.door_keypad_9_garage_side_switch
      - input_boolean.door_keypad_9_4th_bedroom_switch
  door_keypad_10:
    name: Pin Code 10
    entities:
      - input_text.door_keypad_10_name
      - input_text.door_keypad_10_code
      - input_select.door_keypad_10_access_schedule
      - input_datetime.door_keypad_10_date_start
      - input_datetime.door_keypad_10_date_end
      - input_boolean.door_keypad_10_front_switch
      - input_boolean.door_keypad_10_rear_switch
      - input_boolean.door_keypad_10_garage_side_switch
      - input_boolean.door_keypad_10_4th_bedroom_switch

input_text:
  door_keypad_1_name:
    name: Name
  door_keypad_1_code:
    name: Code
  door_keypad_2_name:
    name: Name
  door_keypad_2_code:
    name: Code
  door_keypad_3_name:
    name: Name
  door_keypad_3_code:
    name: Code
  door_keypad_4_name:
    name: Name
  door_keypad_4_code:
    name: Code
  door_keypad_5_name:
    name: Name
  door_keypad_5_code:
    name: Code
  door_keypad_6_name:
    name: Name
  door_keypad_6_code:
    name: Code
  door_keypad_7_name:
    name: Name
  door_keypad_7_code:
    name: Code
  door_keypad_8_name:
    name: Name
  door_keypad_8_code:
    name: Code
  door_keypad_9_name:
    name: Name
  door_keypad_9_code:
    name: Code
  door_keypad_10_name:
    name: Name
  door_keypad_10_code:
    name: Code

input_select:
  door_keypad_1_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_2_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_3_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_4_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_5_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_6_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_7_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_8_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_9_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary
  door_keypad_10_access_schedule:
    name: Access Schedule
    options:
      - Always
      - Recurring
      - Temporary

input_datetime:
  door_keypad_1_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_1_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_2_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_2_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_3_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_3_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_4_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_4_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_5_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_5_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_6_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_6_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_7_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_7_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_8_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_8_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_9_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_9_date_end:
    name: End Time
    has_date: true
    has_time: true
  door_keypad_10_date_start:
    name: Start Time
    has_date: true
    has_time: true
  door_keypad_10_date_end:
    name: End Time
    has_date: true
    has_time: true

input_boolean:
  door_keypad_1_front_switch:
    name: Front Door
  door_keypad_1_rear_switch:
    name: Rear Door
  door_keypad_1_garage_site_switch:
    name: Garage Side Door
  door_keypad_1_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_2_front_switch:
    name: Front Door
  door_keypad_2_rear_switch:
    name: Rear Door
  door_keypad_2_garage_site_switch:
    name: Garage Side Door
  door_keypad_2_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_3_front_switch:
    name: Front Door
  door_keypad_3_rear_switch:
    name: Rear Door
  door_keypad_3_garage_site_switch:
    name: Garage Side Door
  door_keypad_3_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_4_front_switch:
    name: Front Door
  door_keypad_4_rear_switch:
    name: Rear Door
  door_keypad_4_garage_site_switch:
    name: Garage Side Door
  door_keypad_4_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_5_front_switch:
    name: Front Door
  door_keypad_5_rear_switch:
    name: Rear Door
  door_keypad_5_garage_site_switch:
    name: Garage Side Door
  door_keypad_5_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_6_front_switch:
    name: Front Door
  door_keypad_6_rear_switch:
    name: Rear Door
  door_keypad_6_garage_site_switch:
    name: Garage Side Door
  door_keypad_6_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_7_front_switch:
    name: Front Door
  door_keypad_7_rear_switch:
    name: Rear Door
  door_keypad_7_garage_site_switch:
    name: Garage Side Door
  door_keypad_7_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_8_front_switch:
    name: Front Door
  door_keypad_8_rear_switch:
    name: Rear Door
  door_keypad_8_garage_site_switch:
    name: Garage Side Door
  door_keypad_8_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_9_front_switch:
    name: Front Door
  door_keypad_9_rear_switch:
    name: Rear Door
  door_keypad_9_garage_site_switch:
    name: Garage Side Door
  door_keypad_9_4th_bedroom_switch:
    name: 4th Bedroom Door
  door_keypad_10_front_switch:
    name: Front Door
  door_keypad_10_rear_switch:
    name: Rear Door
  door_keypad_10_garage_side_switch:
    name: Garage Side Door
  door_keypad_10_4th_bedroom_switch:
    name: 4th Bedroom Door

#script:
#  door_keypad_1_save:
#    alias: Save
#    sequence:
#      - service: lock.set_usercode
#        data:
#          node_id: 37
#          code_slot: 1
#        data_template:
#          usercode: "{{ states('input_text.door_keypad_1_code') }}"
