automation:
  - alias: "Door Locks"
    trigger:
      - platform: mqtt
        topic: "august/+"
    action:
      - service: notify.html5
        data_template:
          message: >
            The {{ trigger.payload_json.lock }} was {{ trigger.payload_json.state }} by {{ trigger.payload_json.user | trim }} at {{ trigger.payload_json.time | timestamp_custom('%I:%M %p', True) }}.
          title: 'Maravilla: {{ trigger.payload_json.lock }}'
          data:
            requireInteraction: True
sensor:
  - platform: mqtt
    state_topic: august/Front-Door
    name: door_lock_front
    value_template: >
      {%- if value_json.state == 'locked' -%}
        locked
      {%- else -%}
        unlocked
      {%- endif -%}
  - platform: mqtt
    state_topic: august/Rear-Door
    name: door_lock_rear
    value_template: >
      {%- if value_json.state == 'locked' -%}
        locked
      {%- else -%}
        unlocked
      {%- endif -%}
  - platform: mqtt
    state_topic: august/4th-Bedroom
    name: door_lock_4th_bedroom
    value_template: >
      {%- if value_json.state == 'locked' -%}
        locked
      {%- else -%}
        unlocked
      {%- endif -%}
  - platform: template
    sensors:
      door_lock_front_state:
        friendly_name: Front Door
        entity_id: sensor.door_lock_front
        value_template: sensor.door_lock_front.state
        icon_template: >
          {%- if states(sensor.door_lock_front) == 'locked' -%}
            mdi:lock
          {%- else -%}
            mdi:lock-open
          {%- endif -%}
      door_lock_rear_state:
        friendly_name: Rear Door
        entity_id: sensor.door_lock_rear
        value_template: sensor.door_lock_rear.state
        icon_template: >
          {%- if states(sensor.door_lock_rear) == 'locked' -%}
            mdi:lock
          {%- else -%}
            mdi:lock-open
          {%- endif -%}
      door_lock_4th_bedroom_state:
        friendly_name: 4th Bedroom
        entity_id: sensor.door_lock_4th_bedroom
        value_template: sensor.door_lock_4th_bedroom.state
        icon_template: >
          {%- if states(sensor.door_lock_4th_bedroom) == 'locked' -%}
            mdi:lock
          {%- else -%}
            mdi:lock-open
          {%- endif -%}
group:
  door_locks:
    name: Door Locks
    entities:
      - sensor.door_lock_front_state
      - sensor.door_lock_rear_state
      - sensor.door_lock_4th_bedroom_state
