automation:
  - alias: "Door Locks"
    trigger:
      - platform: mqtt
        topic: "august/+"
    action:
      - service: notify.html5
        data_template:
          message: 'Door state changed'
          title: 'Maravilla: State changed'
          data:
            requireInteraction: True
      - service: notify.html5
        data_template:
          message: '{{ trigger.payload_json.lock }}'
          title: 'Maravilla: lock changed'
          data:
            requireInteraction: True
sensor:
  - platform: mqtt
    state_topic: august/Front-Door
    name: door_lock_front
  - platform: mqtt
    state_topic: august/Rear-Door
    name: door_lock_rear
  - platform: mqtt
    state_topic: august/4th-Bedroom
    name: door_lock_4th_bedroom
