#automation:
#  - alias: 1BR Check-in
#    trigger:
#      - platform: time
#        at: '14:45:00'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: calendar.airbnb_1br
#          state: 'on'
#        - condition: template
#          value_template: "{% {{ states.calendar.airbnb_1br.attributes.start_time|replace(' 00:00:00','')|replace('-','') }} == {{ now().year }}{{ now().month }}{{ now().day }} %}"
#    action:
#      - service: lock.set_usercode
#        data:
#          node_id: 11
#          code_slot: 3
#          usercode:
#      - service: variable.set_variable
#        data:
#          variable: airbnb_1br_booking
#          value: '{{ calendar.airbnb_1br.attributes.message }}'
#  - alias: 1BR Check-out
#    trigger:
#      - platform: time
#        at: '12:15:00'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: calendar.airbnb_1br
#          state: 'on'
#    action:
#      - service: lock.set_usercode
#        data:
#          node: 11
#          codeslot: 3
#          usercode: !secret 1br_temp_code

group:
  door_keypad_front_1:
    name: Front Door Pin Code 1
    entities:
      - input_text.door_keypad_front_1_name
      - input_text.door_keypad_front_1_code
  door_keypad_front_2:
    name: Front Door Pin Code 2
    entities:
      - input_text.door_keypad_front_2_name
      - input_text.door_keypad_front_2_code
  door_keypad_front_3:
    name: Front Door Pin Code 3
    entities:
      - input_text.door_keypad_front_3_name
      - input_text.door_keypad_front_3_code
  door_keypad_front_4:
    name: Front Door Pin Code 4
    entities:
      - input_text.door_keypad_front_4_name
      - input_text.door_keypad_front_4_code
  door_keypad_front_5:
    name: Front Door Pin Code 5
    entities:
      - input_text.door_keypad_front_5_name
      - input_text.door_keypad_front_5_code
  door_keypad_front_6:
    name: Front Door Pin Code 6
    entities:
      - input_text.door_keypad_front_6_name
      - input_text.door_keypad_front_6_code
  door_keypad_front_7:
    name: Front Door Pin Code 7
    entities:
      - input_text.door_keypad_front_7_name
      - input_text.door_keypad_front_7_code
  door_keypad_front_8:
    name: Front Door Pin Code 8
    entities:
      - input_text.door_keypad_front_8_name
      - input_text.door_keypad_front_8_code
  door_keypad_front_9:
    name: Front Door Pin Code 9
    entities:
      - input_text.door_keypad_front_9_name
      - input_text.door_keypad_front_9_code
  door_keypad_front_10:
    name: Front Door Pin Code 10
    entities:
      - input_text.door_keypad_front_10_name
      - input_text.door_keypad_front_10_code
  door_keypad_rear:
    name: Rear Door Keypad
    entities:
      - input_text.door_keypad_rear_name
  door_keypad_garage_side:
    name: Garage Side Door Keypad
    entities:
      - input_text.door_keypad_garage_side_name
  door_keypad_4th_bedroom:
    name: 4th Bedroom Door Keypad
    entities:
      - input_text.door_keypad_4th_bedroom_name

input_text:
  door_keypad_front_1_name:
    name: Name
  door_keypad_front_1_code:
    name: Code
  door_keypad_front_2_name:
    name: Name
  door_keypad_front_2_code:
    name: Code
  door_keypad_front_3_name:
    name: Name
  door_keypad_front_3_code:
    name: Code
  door_keypad_front_4_name:
    name: Name
  door_keypad_front_4_code:
    name: Code
  door_keypad_front_5_name:
    name: Name
  door_keypad_front_5_code:
    name: Code
  door_keypad_front_6_name:
    name: Name
  door_keypad_front_6_code:
    name: Code
  door_keypad_front_7_name:
    name: Name
  door_keypad_front_7_code:
    name: Code
  door_keypad_front_8_name:
    name: Name
  door_keypad_front_8_code:
    name: Code
  door_keypad_front_9_name:
    name: Name
  door_keypad_front_9_code:
    name: Code
  door_keypad_front_10_name:
    name: Name
  door_keypad_front_10_code:
    name: Code
  door_keypad_rear_name:
    name: Name
  door_keypad_garage_side_name:
    name: Name
  door_keypad_4th_bedroom_name:
    name: Name

script:
  door_keypad_front_save:
    alias: Save
    sequence:
      - service: input_number.set_value

