sensor:
  - platform: template
    sensors:
      door_batteries_door_fourth_bedroom:
        value_template: '{{states["zwave"]["door_fourth_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Fourth Bedroom
        unit_of_measurement: '%'
      door_batteries_door_front_door:
        value_template: '{{states["zwave"]["door_front_door"]["attributes"]["battery_level"]}}'
        friendly_name: Front Door
        unit_of_measurement: '%'
      door_batteries_door_garage_interior:
        value_template: '{{states["zwave"]["door_garage_interior"]["attributes"]["battery_level"]}}'
        friendly_name: Garage (interior)
        unit_of_measurement: '%'
      door_batteries_door_garage_side:
        value_template: '{{states["zwave"]["door_garage_side"]["attributes"]["battery_level"]}}'
        friendly_name: Garage (side door)
        unit_of_measurement: '%'
      door_batteries_door_rear_door:
        value_template: '{{states["zwave"]["door_rear_door"]["attributes"]["battery_level"]}}'
        friendly_name: Rear Door
        unit_of_measurement: '%'
      door_batteries_door_rear_door:
        value_template: '{{states["zwave"]["door_rear_door"]["attributes"]["battery_level"]}}'
        friendly_name: Rear Door
        unit_of_measurement: '%'
      slider_batteries_slider_fourth_bedroom:
        value_template: '{{states["zwave"]["slider_fourth_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Fourth Bedroom
        unit_of_measurement: '%'
      slider_batteries_slider_living_room:
        value_template: '{{states["zwave"]["slider_living_room"]["attributes"]["battery_level"]}}'
        friendly_name: Living Room
        unit_of_measurement: '%'
      slider_batteries_slider_master_bedroom:
        value_template: '{{states["zwave"]["slider_master_bedroom"]["attributes"]["battery_level"]}}'
        friendly_name: Master Bedroom
        unit_of_measurement: '%'
group:
  doors:
    name: Doors
    entities:
      - binary_sensor.door_fourth_bedroom_sensor
      - binary_sensor.door_front_door_sensor
      - binary_sensor.door_garage_interior_sensor
      - binary_sensor.door_garage_side_sensor
      - binary_sensor.door_rear_door_sensor
      - binary_sensor.slider_fourth_bedroom_sensor
      - binary_sensor.slider_living_room_sensor
      - binary_sensor.slider_master_bedroom_sensor
  door_batteries:
    name: Doors
    entities:
      - sensor.door_batteries_door_fourth_bedroom
      - sensor.door_batteries_door_front_door
      - sensor.door_batteries_door_garage_interior
      - sensor.door_batteries_door_garage_side
      - sensor.door_batteries_door_rear_door
  slider_batteries:
    name: Sliding Doors
    entities:
      - sensor.slider_batteries_sliderfourth_bedroom
      - sensor.slider_batteries_slider_living_room
      - sensor.slider_batteries_slider_master_bedroom
