homeassistant: !include config/homeassistant.yaml
introduction:
frontend:
config:
http: !include config/http.yaml
updater:
discovery:
conversation:
history:
logbook:
sun:
zwave:
  usb_path: /dev/ttyACM0
sensor: !include config/sensors.yaml
tts: !include config/tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
packages: !include_dir_named config/packages
