homeassistant: !include config/homeassistant.yaml
frontend:
config:
http: !include config/http.yaml
updater:
discovery:
conversation:
history:
logbook:
sun:
zwave:
  usb_path: /dev/ttyACM0
tts: !include config/tts.yaml
group: !include_dir_merge_named config/groups/
#automation: !include_dir_merge_list config/automations/
notify: !include config/notifications.yaml
