homeassistant: !include config/homeassistant.yaml
frontend:
config:
http: !include config/http.yaml
updater:
discovery:
conversation:
history:
logbook:
sun:
zwave:
  usb_path: /dev/ttyACM0
tts: !include config/tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
