homeassistant: !include config/homeassistant.yaml
introduction:
frontend:
config:
http: !include config/http.yaml
updater:
discovery:
conversation:
history:
logbook:
sun:
tts: !include config/tts.yaml
group: !include groups.yaml
automation: !include automations.yaml
