- alias: Fire Alarm Battery Good
  trigger:
    - platform: numeric_state
      entity_id: sensor.fire_alarm_batteries_master_bedroom, sensor.fire_alarm_batteries_second_bedroom, sensor.fire_alarm_batteries_third_bedroom, sensor.fire_alarm_batteries_fourth_bedroom, sensor.fire_alarm_batteries_hallway, sensor.fire_alarm_batteries_hallway_2, sensor.fire_alarm_batteries_hallway_3, sensor.fire_alarm_batteries_dining
      above: 97.9
  action:
    service: customizer.set_attribute
    rgb_color: "[0, 0, 0]"
    data_template:
      entity_id: "{{trigger.entity_id}}"
- alias: Fire Alarm Battery Fair
  trigger:
    - platform: numeric_state
      entity_id: sensor.fire_alarm_batteries_master_bedroom, sensor.fire_alarm_batteries_second_bedroom, sensor.fire_alarm_batteries_third_bedroom, sensor.fire_alarm_batteries_fourth_bedroom, sensor.fire_alarm_batteries_hallway, sensor.fire_alarm_batteries_hallway_2, sensor.fire_alarm_batteries_hallway_3, sensor.fire_alarm_batteries_dining
      above: 96.8
      below: 98
  action:
    service: customizer.set_attribute
    rgb_color: "[255, 255, 0]"
    data_template:
      entity_id: "{{trigger.entity_id}}"
- alias: Fire Alarm Battery Poor
  trigger:
    - platform: numeric_state
      entity_id: sensor.fire_alarm_batteries_master_bedroom, sensor.fire_alarm_batteries_second_bedroom, sensor.fire_alarm_batteries_third_bedroom, sensor.fire_alarm_batteries_fourth_bedroom, sensor.fire_alarm_batteries_hallway, sensor.fire_alarm_batteries_hallway_2, sensor.fire_alarm_batteries_hallway_3, sensor.fire_alarm_batteries_dining
      below: 97
  action:
    service: customizer.set_attribute
    rgb_color: "[255, 0, 0]"
    data_template:
      entity_id: "{{trigger.entity_id}}"
