- alias: Garage open
  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'
      for:
        seconds: 30
  action:
    - service: cover.close_cover
      entity: cover.garage_door
