- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.html5
      data_template:
        title: "Hass.io update available"
        message: "{{ states.updater.updater.state }} is available for Hass.io at Avenida Maravilla"
        data:
          requireInteraction: True