"sensor.*_batteries_*":
  custom_ui_state_card: state-card-custom-ui
  templates:
    theme: >
      return (entity.state < 97 && entity.state > 0) ? 'red' : (entity.state < 99 && entity.state > 97) ? 'yellow' : 'default';
