"sensor.*_access_control":
  hidden: true
"sensor.*_alarm_level":
  hidden: true
"sensor.*_alarm_type":
  hidden: true
"sensor.*_sourcenodeid":
  hidden: true
"sensor.*_burglar":
  hidden: true
group.all_*:
  hidden: true