group.keypads:
  order: 10
group.keypads_maids:
  order: 11
group.keypads_airbnb:
  order: 12
group.all_locks:
  friendly_name: Locks
  hidden: false
group.all_automations:
  hidden: false
group.dev:
  order: 99
lock.lock_4thbedroom_door_locked:
  friendly_name: 4th Bedroom Door
lock.lock_front_door_locked:
  friendly_name: Front Door
lock.lock_garageside_door_locked:
  friendly_name: Garage Side Door
lock.lock_rear_door_locked:
  friendly_name: Rear Door
