"sensor.*_batteries_*":
  custom_ui_state_card: state-card-custom-ui
  templates:
    theme: >
      if (entity.state < 97 && entity.state > 0) {
        return 'red';
      }
      if (entity.state < 99 && entity.state > 97) {
        return 'yellow';
      }
      if (entity.state == 100) {
        return 'default';
      }
