broker: !secret mqtt_broker
port: !secret mqtt_port
keepalive: 60
username: !secret mqtt_username
password: !secret mqtt_password
protocol: 3.1
client_cert: !secret mqtt_client_cert
client_key: !secret mqtt_client_key
