default_view:
  name: Home
  view: yes
  icon: mdi:home
  entities:
    - group.all_locks
    - group.doors
    - group.windows
    - group.garage
    - group.thermostat
    - group.fire_alarms
    - media_player.roku_5s56d1020224
    - history_graph.temperature
