fire_alarms:
  name: Fire Alarms
  entities:
    - sensor.fire_alarm_batteries_master_bedroom
    - sensor.fire_alarm_batteries_second_bedroom
    - sensor.fire_alarm_batteries_third_bedroom
    - sensor.fire_alarm_batteries_fourth_bedroom
    - sensor.fire_alarm_batteries_hallway
    - sensor.fire_alarm_batteries_hallway_2
    - sensor.fire_alarm_batteries_hallway_3
    - sensor.fire_alarm_batteries_dining