fire_alarms:
  name: Fire Alarms
  entities:
    - sensor.fire_alarm_master_bedroom
    - sensor.fire_alarm_second_bedroom
    - sensor.fire_alarm_third_bedroom
    - sensor.fire_alarm_fourth_bedroom
    - sensor.fire_alarm_hallway
    - sensor.fire_alarm_hallway_2
    - sensor.fire_alarm_hallway_3
    - sensor.fire_alarm_dining